export const selectors = {
    //sign up page
  Sign_up: '/html/body/section/div[2]/div[1]/div/div[2]/a[3]',
  User_id: '/html/body/section/div[2]/div[2]/div/div/form/table[1]/tbody/tr[1]/td[2]/input',
  password: '/html/body/section/div[2]/div[2]/div/div/form/table[1]/tbody/tr[2]/td[2]/input',
  confirm_password: '/html/body/section/div[2]/div[2]/div/div/form/table[1]/tbody/tr[3]/td[2]/input',
  firstname: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[1]/td[2]/input',
  lastname: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[2]/td[2]/input',
  email_field: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[3]/td[2]/input',
  phone: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[4]/td[2]/input',
  address1: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[5]/td[2]/input',
  address2: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[6]/td[2]/input',
  city: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[7]/td[2]/input',
  state: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[8]/td[2]/input',
  zip: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[9]/td[2]/input',
  country: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[10]/td[2]/input',
  language: '/html/body/section/div[2]/div[2]/div/div/form/table[3]/tbody/tr[1]/td[2]/select',
  fav_category: '/html/body/section/div[2]/div[2]/div/div/form/table[3]/tbody/tr[2]/td[2]/select',
  mylist: '/html/body/section/div[2]/div[2]/div/div/form/table[3]/tbody/tr[3]/td[2]/input',
  mybanner: '/html/body/section/div[2]/div[2]/div/div/form/table[3]/tbody/tr[4]/td[2]/input',
  saveinfo: '/html/body/section/div[2]/div[2]/div/div/form/div/button',
//sign in page
  sign_in: '/html/body/section/div[2]/div[1]/div/div[2]/a[2]',
  username: '/html/body/section/div[2]/div[2]/div/div/div[1]/div/form/div[1]/input',
  login_password: '/html/body/section/div[2]/div[2]/div/div/div[1]/div/form/div[2]/input',
  login_btn: '/html/body/section/div[2]/div[2]/div/div/div[1]/div/form/div[3]/button',
//Add to cart
cart_body: '/html/body/section/div[2]/div[2]',
//fish category
fish_ctgry: '/html/body/section/div[2]/div[2]/div[2]/div[1]/div/h4[1]/a',
koi_productid: '/html/body/section/div[2]/div[2]/table/tbody/tr[3]/td[1]/a',
spotless_koi_cart_btn:'/html/body/section/div[2]/div[2]/table/tbody/tr[2]/td[5]/a',
return_to_main_menu_btn: '/html/body/section/div[2]/div[2]/div[1]/a',
angelfish_productid: '/html/body/section/div[2]/div[2]/table/tbody/tr[1]/td[1]/a',
small_angelfish_cart_btn: '/html/body/section/div[2]/div[2]/table/tbody/tr[2]/td[5]/a',
tigershark_productid: '/html/body/section/div[2]/div[2]/table/tbody/tr[2]/td[1]/a',
tigershark_itemid: '/html/body/section/div[2]/div[2]/table/tbody/tr/td[1]/a',
tigershark_cart_btn: '/html/body/section/div[2]/div[2]/div[3]/a',
goldfish_productid: '/html/body/section/div[2]/div[2]/table/tbody/tr[4]/td[1]/a',
adult_female_goldfish_cart_btn: '/html/body/section/div[2]/div[2]/table/tbody/tr[2]/td[5]/a',
//dogs category
dogs_ctgry: '/html/body/section/div[2]/div[2]/div/div[1]/div/h4[2]/a',
bulldog_productid: '/html/body/section/div[2]/div[2]/table/tbody/tr[1]/td[1]/a',
male_adult_bulldog_cart_btn: '/html/body/section/div[2]/div[2]/table/tbody/tr[1]/td[5]/a',
quantity: '/html/body/section/div[2]/div[2]/form/table/tbody/tr/td[5]/input',
poodle_productid: '/html/body/section/div[2]/div[2]/table/tbody/tr[2]/td[1]/a',
poodle_itemid: '/html/body/section/div[2]/div[2]/table/tbody/tr/td[1]/a',
poodle_cart_btn: '/html/body/section/div[2]/div[2]/div[3]/a',
dalmation_product_id: '/html/body/section/div[2]/div[2]/table/tbody/tr[3]/td[1]/a',
Spotted_Adult_Female_Dalmation_cart_btn: '/html/body/section/div[2]/div[2]/table/tbody/tr[2]/td[5]/a',
golden_retriever_produt_id: '/html/body/section/div[2]/div[2]/table/tbody/tr[4]/td[1]/a',
adult_female_golden_retriever_cart_btn: '/html/body/section/div[2]/div[2]/table/tbody/tr/td[5]/a',
labrador_retriever_product_id: '/html/body/section/div[2]/div[2]/table/tbody/tr[5]/td[1]/a',
adult_male_labrador_retriever_cart_btn: '/html/body/section/div[2]/div[2]/table/tbody/tr[3]/td[5]/a',
chihuahua_productid: '/html/body/section/div[2]/div[2]/table/tbody/tr[6]/td[1]/a',
adult_female_chihuahua_cartbtn: '/html/body/section/div[2]/div[2]/table/tbody/tr[2]/td[5]/a',
//cat category
cat_ctrgy: '/html/body/section/div[2]/div[2]/div/div[1]/div/h4[3]/a',
manx_product_id: '/html/body/section/div[2]/div[2]/table/tbody/tr[1]/td[1]/a',
tailless_manx_item_id: '/html/body/section/div[2]/div[2]/table/tbody/tr[1]/td[1]/a',
taillessmanx_crt_btn: '/html/body/section/div[2]/div[2]/table/tbody/tr[1]/td[5]/a',
persian_product_id: '/html/body/section/div[2]/div[2]/table/tbody/tr[2]/td[1]/a',
adult_male_persian_crt_btn: '/html/body/section/div[2]/div[2]/table/tbody/tr[2]/td[5]/a',
//reptiles category
reptiles_ctgry: '/html/body/section/div[2]/div[2]/div[2]/div[1]/div/h4[4]/a',
rattlesnake_product_id: '/html/body/section/div[2]/div[2]/table/tbody/tr[1]/td[1]/a',
venomless_rattlesnake_itemid: '/html/body/section/div[2]/div[2]/table/tbody/tr[1]/td[1]/a',
venomless_rattlesnake_crt_btn: '/html/body/section/div[2]/div[2]/div[3]/a',
iguana_product_id: '/html/body/section/div[2]/div[2]/table/tbody/tr[2]/td[1]/a',
green_adult_iguana_crt_btn: '/html/body/section/div[2]/div[2]/table/tbody/tr/td[5]/a',
//birds category
birds_ctgry: '/html/body/section/div[2]/div[2]/div[2]/div[1]/div/h4[5]/a',
amazon_parrot_product_id: '/html/body/section/div[2]/div[2]/table/tbody/tr[1]/td[1]/a',
adult_male_amazonparrot_itemid: '/html/body/section/div[2]/div[2]/table/tbody/tr/td[1]/a',
adult_male_amazonparrot_crtbtn: '/html/body/section/div[2]/div[2]/div[3]/a',
finch_product_id: '/html/body/section/div[2]/div[2]/table/tbody/tr[2]/td[1]/a',
adult_male_finch_crtbtn: '/html/body/section/div[2]/div[2]/table/tbody/tr/td[5]/a',
//
update_btn: '/html/body/section/div[2]/div[2]/form/table/tfoot/tr/td[2]/button',
item_price: '/html/body/section/div[2]/div[2]/form/table/tbody/tr/td[6]',
total_cost:'/html/body/section/div[2]/div[2]/form/table/tbody/tr/td[7]',
//remove item from cart
remove_aitem_btn: '/html/body/section/div[2]/div[2]/form/table/tbody/tr/td[8]/a',
remove_all_btn: '/html/body/section/div[2]/div[2]/form/table/tfoot/tr/td[5]/a',
cart_btn: '/html/body/section/div[2]/div[1]/div/div[2]/a[1]',
//checkout
checkout_btn: '/html/body/section/div[2]/div[2]/div[2]/a',
card_type: '/html/body/section/div[2]/div[2]/div/div/form/table[1]/tbody/tr[1]/td[2]/select',
card_no: '/html/body/section/div[2]/div[2]/div/div/form/table[1]/tbody/tr[2]/td[2]/input',
expiry_date: '/html/body/section/div[2]/div[2]/div/div/form/table[1]/tbody/tr[3]/td[2]/input',
checkout_firstname: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[1]/td[2]/input',
checkout_lastname: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[2]/td[2]/input',
checkout_address1: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[3]/td[2]/input',
checkout_address2: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[4]/td[2]/input',
checkout_city: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[4]/td[2]/input',
checkout_state: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[6]/td[2]/input',
checkout_zip: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[7]/td[2]/input',
checkout_country: '/html/body/section/div[2]/div[2]/div/div/form/table[2]/tbody/tr[8]/td[2]/input',
checkout_continue_btn: '/html/body/section/div[2]/div[2]/div/div/form/div/button',
confirm_btn: '/html/body/section/div[2]/div[2]/div/div/form/div/button',
delete_btn: '/html/body/section/div[2]/div[2]/div/div/div[3]/button',

};